- id: '1607462965576'
  alias: Road condition and weather forecast import
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /10
  condition: []
  action:
  - service: shell_command.vedurspa
    data: {}
  mode: single
